### ISSUE TITLE
Develop checklist for protocols release

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer-protocols#122]
Includes stuff in #118.
- [ ] the changes show correct formatting when built with Sphinx;
- [ ] the changes have been reviewed by someone other than the original author;
- [ ] the changes work under our literate-resting tests with a small data set;
- [ ] bumped version number, created tag, set tag to default on RTD;
